<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'name' => 'Shenal',
                'email' => 'shenal@gmail.com',
                'mobile' => '0710000001',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E501',
                'regement_no' => 'R501',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000001',
                'armyId' => 'DE00001',
                'officeAddress' => 'Batharamulla',
                'role' => 'Admin',
            ],
            [
                'name' => 'Lahiru',
                'email' => 'lahiru@gmail.com',
                'mobile' => '0710000002',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E502',
                'regement_no' => 'R502',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000002',
                'armyId' => 'DE00002',
                'officeAddress' => 'Batharamulla',
                'role' => 'Account SO',
            ],
            [
                'name' => 'Aravinda',
                'email' => 'aravinda@gmail.com',
                'mobile' => '0710000003',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E503',
                'regement_no' => 'R503',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000003',
                'armyId' => 'DE00003',
                'officeAddress' => 'Batharamulla',
                'role' => 'Unit OC',
            ],
            [
                'name' => 'Aruna',
                'email' => 'aruna@gmail.com',
                'mobile' => '0710000004',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E504',
                'regement_no' => 'R504',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000004',
                'armyId' => 'DE00004',
                'officeAddress' => 'Batharamulla',
                'role' => 'Loan Clerk',
            ],
            [
                'name' => 'Ashri',
                'email' => 'ashri@gmail.com',
                'mobile' => '0710000005',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E505',
                'regement_no' => 'R505',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000005',
                'armyId' => 'DE00005',
                'officeAddress' => 'Batharamulla',
                'role' => 'Unit Clerk',
            ],
            [
                'name' => 'Bimal',
                'email' => 'bimal@gmail.com',
                'mobile' => '0710000006',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E506',
                'regement_no' => 'R506',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000006',
                'armyId' => 'DE00006',
                'officeAddress' => 'Batharamulla',
                'role' => 'Shop Coord Clerk',
            ],
            [
                'name' => 'janith',
                'email' => 'janith@gmail.com',
                'mobile' => '0710000007',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E507',
                'regement_no' => 'R507',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000007',
                'armyId' => 'DE00007',
                'officeAddress' => 'Batharamulla',
                'role' => 'Membership Clerk',
            ],
            [
                'name' => 'januth',
                'email' => 'januth@gmail.com',
                'mobile' => '0710000008',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E508',
                'regement_no' => 'R508',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000008',
                'armyId' => 'DE00008',
                'officeAddress' => 'Batharamulla',
                'role' => 'Membership OC',
            ],
            [
                'name' => 'jayathilaka',
                'email' => 'jayee@gmail.com',
                'mobile' => '0710000009',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E509',
                'regement_no' => 'R509',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000009',
                'armyId' => 'DE00009',
                'officeAddress' => 'Batharamulla',
                'role' => 'Shop Coord OC',
            ],
            [
                'name' => 'kamal',
                'email' => 'kamal@gmail.com',
                'mobile' => '0710000010',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E510',
                'regement_no' => 'R510',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000010',
                'armyId' => 'DE00010',
                'officeAddress' => 'Batharamulla',
                'role' => 'Loan OC',
            ],
            [
                'name' => 'kamal',
                'email' => 'kamal@gmail.com',
                'mobile' => '0710000010',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E510',
                'regement_no' => 'R510',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000010',
                'armyId' => 'DE00010',
                'officeAddress' => 'Batharamulla',
                'role' => 'Loan OC',
            ],
            [
                'name' => 'Isuru',
                'email' => 'isuru@gmail.com',
                'mobile' => '0710000011',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E511',
                'regement_no' => 'R511',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000011',
                'armyId' => 'DE00011',
                'officeAddress' => 'Batharamulla',
                'role' => 'Staff Officer',
            ],
            [
                'name' => 'Naveen',
                'email' => 'naveen@gmail.com',
                'mobile' => '0710000012',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E512',
                'regement_no' => 'R512',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000012',
                'armyId' => 'DE00012',
                'officeAddress' => 'Batharamulla',
                'role' => 'Welfare Shop Clerk',
            ],
            [
                'name' => 'Nuwan',
                'email' => 'nuwan@gmail.com',
                'mobile' => '0710000013',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E513',
                'regement_no' => 'R513',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000013',
                'armyId' => 'DE00013',
                'officeAddress' => 'Batharamulla',
                'role' => 'Welfare Shop Clerk',
            ],
            [
                'name' => 'Suneth',
                'email' => 'suneth@gmail.com',
                'mobile' => '0710000014',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E514',
                'regement_no' => 'R514',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000014',
                'armyId' => 'DE00014',
                'officeAddress' => 'Batharamulla',
                'role' => 'Welfare Shop OC',
            ],
            [
                'name' => 'Ruwan',
                'email' => 'ruwan@gmail.com',
                'mobile' => '0710000015',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E515',
                'regement_no' => 'R515',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000015',
                'armyId' => 'DE00015',
                'officeAddress' => 'Batharamulla',
                'role' => 'Welfare Shop OC',
            ],
            [
                'name' => 'Vijay',
                'email' => 'vijay@gmail.com',
                'mobile' => '0710000016',
                'address' => 'PahalaYagoda, Ganemulla',
                'employee_no' => 'E516',
                'regement_no' => 'R516',
                'regement_id' => 1,
                'unit_id' => 1,
                'rank_id' => 1,
                'password' => Hash::make('123456789'),
                'nic' => '199900000016',
                'armyId' => 'DE00016',
                'officeAddress' => 'Batharamulla',
                'role' => 'User',
            ],
        ];

        foreach ($users as $userData) {
            $existingUser = User::where('email', $userData['email'])->first();

            if (!$existingUser) {
                User::create($userData);
                echo "✅ User '{$userData['name']}' created successfully.\n";
            } else {
                echo "⚠️ User '{$userData['name']}' already exists.\n";
            }
        }
    }
}
